### ISSUE TITLE
Fix CI failing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgemagic-rs#3]
CI is failing. Please fix it.

**Comment by mgjm** [comment]
Fixed with 03fa966.

@mariobehling Can you give me owner permissions for this repo. I want to setup branch protection rules, to prevent pushing code with failing CI in the future.

**Comment by mariobehling** [comment]
@mgjm Please try again.

**Comment by mgjm** [comment]
Thanks, I've added a branch protection ruleset now.
